# Generated by Django 3.1.7 on 2021-04-01 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0007_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_products', models.IntegerField()),
                ('product_price', models.FloatField()),
                ('id_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bboard.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bboard.product')),
            ],
        ),
        migrations.RenameModel(
            old_name='Purchase',
            new_name='Order',
        ),
        migrations.DeleteModel(
            name='Purchase_Position',
        ),
    ]
