# Generated by Django 3.1.7 on 2021-04-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0010_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_address',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
