# Generated by Django 3.1.7 on 2021-04-06 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0011_auto_20210403_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_address',
        ),
    ]
