# Generated by Django 3.1.7 on 2021-04-06 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0013_auto_20210406_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='id_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bboard.order'),
        ),
    ]
