# Generated by Django 3.1.7 on 2021-04-06 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0014_orderline_id_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='id_cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bboard.cart'),
        ),
    ]
